Repository VanSubstance/capstone_AppPal, pull requests merged in 2022-06, with the labels that each got.

#26 Add(Build basic socket server for python)
  pythonServer/gestureRegognizer.py
  pythonServer/models/model.h5
  pythonServer/models/model2_1.0.h5
  pythonServer/socketServer.py
  pythonServer/test.py
Labels: Synchronize

#29 add(Application)
  application/app/src/main/java/com/example/apppal/GestureRecognitionSocket.java
  application/app/src/main/java/com/example/apppal/MainActivity.java
Labels: development

#34 Application
  .gitignore
  Application.drawio
  application/.gitignore
  application/.idea/.gitignore
  application/.idea/.name
  application/.idea/compiler.xml
  application/.idea/gradle.xml
  application/.idea/misc.xml
  application/.idea/vcs.xml
  application/app/.gitignore
  application/app/build.gradle
  application/app/proguard-rules.pro
  application/app/src/main/AndroidManifest.xml
  application/app/src/main/java/com/example/apppal/GestureRecognitionSocket.java
  application/app/src/main/java/com/example/apppal/Handler/SocketReceiveHandler.java
  application/app/src/main/java/com/example/apppal/HandsResultGlRenderer.java
  application/app/src/main/java/com/example/apppal/HandsResultImageView.java
  application/app/src/main/java/com/example/apppal/MainActivity.java
  application/app/src/main/java/com/example/apppal/ServerConnection.java
  application/app/src/main/java/com/example/apppal/Storage/GlobalState.java
  application/app/src/main/java/com/example/apppal/Utils.java
  application/app/src/main/java/com/example/apppal/VO/CoordinateInfo.java
  application/app/src/main/java/com/example/apppal/VO/GestureType.java
  application/app/src/main/java/com/example/apppal/VO/SocketFunctionType.java
  application/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  application/app/src/main/res/drawable/button_round.xml
  application/app/src/main/res/drawable/ic_launcher_background.xml
  application/app/src/main/res/layout/activity_main.xml
  application/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  application/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  application/app/src/main/res/mipmap-hdpi/ic_launcher.png
  application/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  application/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  application/app/src/main/res/mipmap-mdpi/ic_launcher.png
  application/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  application/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  application/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  application/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  application/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  application/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  application/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  application/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  application/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  application/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  application/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  application/app/src/main/res/values/colors.xml
  application/app/src/main/res/values/strings.xml
  application/app/src/main/res/values/styles.xml
  application/build.gradle
  application/gradle.properties
  application/gradle/wrapper/gradle-wrapper.jar
  application/gradle/wrapper/gradle-wrapper.properties
  application/gradlew
  application/gradlew.bat
  application/settings.gradle
  pythonServer/app.py
  pythonServer/gestureRegognizer.py
  pythonServer/models/model.h5
  pythonServer/models/model2_1.0.h5
Labels: Synchronize

#35 Socket server
  SocketServer/.gitignore
  SocketServer/gestureRecognizer.py
  SocketServer/models/v.1.0/model.h5
  SocketServer/server.py
  pythonServer/app.py
  pythonServer/gestureRegognizer.py
  pythonServer/models/model.h5
  pythonServer/models/model2_1.0.h5
Labels: Synchronize

#41 Add(Text visualization)
  application/app/src/main/java/com/example/apppal/Handler/ModeGestureHandler.java
  application/app/src/main/java/com/example/apppal/Handler/SocketReceiveHandler.java
  application/app/src/main/java/com/example/apppal/MainActivity.java
  application/app/src/main/java/com/example/apppal/Storage/GlobalState.java
  application/app/src/main/java/com/example/apppal/Utils.java
  application/app/src/main/res/layout/activity_main.xml
Labels: development, enhancement, good first issue
