Repository VanSubstance/capstone_AppPal, pull requests merged in 2022-09, with the labels that each got.

#59 add(Hand detection)
  application_new/app/build.gradle
  application_new/app/src/main/java/com/capstone/apppal/DrawARActivity.java
  application_new/app/src/main/java/com/capstone/apppal/rendering/LineShaderRenderer.java
Labels: development, enhancement, Synchronize

#61 Application
  application_new/app/build.gradle
  application_new/app/src/main/java/com/capstone/apppal/AppSettings.java
  application_new/app/src/main/java/com/capstone/apppal/DrawARActivity.java
  application_new/app/src/main/java/com/capstone/apppal/model/Stroke.java
  application_new/app/src/main/java/com/capstone/apppal/rendering/LineShaderRenderer.java
  application_new/app/src/main/java/com/capstone/apppal/view/ColorSelector.java
  application_new/app/src/main/java/com/capstone/apppal/view/ToolSelector.java
  application_new/app/src/main/res/drawable/ic_color_black.xml
  application_new/app/src/main/res/drawable/ic_color_blue.xml
  application_new/app/src/main/res/drawable/ic_color_green.xml
  application_new/app/src/main/res/drawable/ic_color_red.xml
  application_new/app/src/main/res/drawable/ic_selection_cube.xml
  application_new/app/src/main/res/drawable/ic_selection_oval.xml
  application_new/app/src/main/res/drawable/ic_selection_rect.xml
  application_new/app/src/main/res/drawable/ic_selection_straight_line.xml
  application_new/app/src/main/res/layout/activity_main.xml
  application_new/app/src/main/res/layout/view_color_selector.xml
  application_new/app/src/main/res/layout/view_tool_selector.xml
  application_new/app/src/main/res/raw/line_vert.glsl
  application_new/app/src/main/res/values/strings.xml
Labels: Synchronize

#69 feat(Connect application to server)
  application_new/app/src/main/java/com/capstone/apppal/HandTracking.java
  application_new/app/src/main/java/com/capstone/apppal/VO/GestureType.java
  application_new/app/src/main/java/com/capstone/apppal/network/GestureRecognitionSocket.java
  application_new/app/src/main/java/com/capstone/apppal/network/SocketConnection.java
  application_new/app/src/main/java/com/capstone/apppal/network/handler/ModeGestureHandler.java
  application_new/app/src/main/java/com/capstone/apppal/network/handler/SocketReceiveHandler.java
  application_new/app/src/main/java/com/capstone/apppal/utils/GlobalState.java
Labels: development, enhancement, Synchronize

#74 feat(AWS Connection)
  .DS_Store
  application_new/app/src/main/java/com/capstone/apppal/VO/GestureType.java
  application_new/app/src/main/java/com/capstone/apppal/network/handler/SocketReceiveHandler.java
  application_new/app/src/main/java/com/capstone/apppal/utils/GlobalState.java
Labels: development, enhancement, Synchronize

#78 77 calculating ratio for extending x y coordinates for drawing with hand
  application_new/app/src/main/java/com/capstone/apppal/HandTracking.java
  application_new/app/src/main/java/com/capstone/apppal/rendering/LineUtils.java
Labels: enhancement, Synchronize

#80 67 interaction between hand and uiux
  application_new/app/src/main/java/com/capstone/apppal/DrawARActivity.java
  application_new/app/src/main/java/com/capstone/apppal/HandTracking.java
  application_new/app/src/main/java/com/capstone/apppal/VO/FunctionType.java
  application_new/app/src/main/java/com/capstone/apppal/network/GestureRecognitionSocket.java
  application_new/app/src/main/java/com/capstone/apppal/network/handler/ModeGestureHandler.java
  application_new/app/src/main/java/com/capstone/apppal/network/handler/SocketReceiveHandler.java
  application_new/app/src/main/java/com/capstone/apppal/utils/GlobalState.java
  application_new/app/src/main/java/com/capstone/apppal/view/BrushSelector.java
  application_new/app/src/main/java/com/capstone/apppal/view/ColorSelector.java
  application_new/app/src/main/java/com/capstone/apppal/view/MenuSelector.java
  application_new/app/src/main/java/com/capstone/apppal/view/SelectedOption.java
  application_new/app/src/main/java/com/capstone/apppal/view/ToolSelector.java
  application_new/app/src/main/res/drawable/selected_option_bg.xml
  application_new/app/src/main/res/layout/activity_main.xml
  application_new/app/src/main/res/layout/view_main_selector.xml
  application_new/app/src/main/res/layout/view_selected_option.xml
  application_new/app/src/main/res/values/dimens.xml
  application_new/app/src/main/res/values/strings.xml
Labels: development, enhancement, Synchronize

#84 add(Enabling Depth test)
  application_new/app/src/main/java/com/capstone/apppal/rendering/LineShaderRenderer.java
Labels: development, enhancement

#92 add(Option Dialog)
  application_new/app/src/main/java/com/capstone/apppal/view/dialog/ChoiceDialog.java
  application_new/app/src/main/java/com/capstone/apppal/view/dialog/ConfirmDialog.java
  application_new/app/src/main/java/com/capstone/apppal/view/fragments/ListFragment.java
  application_new/app/src/main/res/drawable/divider_10dp.xml
  application_new/app/src/main/res/layout/dialog_choice.xml
Labels: development, enhancement

#96 93 implementation of functions for room
  application_new/app/src/main/java/com/capstone/apppal/DrawARActivity.java
  application_new/app/src/main/java/com/capstone/apppal/OnBoardingActivity.java
  application_new/app/src/main/java/com/capstone/apppal/RoomHandler.java
  application_new/app/src/main/java/com/capstone/apppal/VO/RoomsInfo.java
  application_new/app/src/main/java/com/capstone/apppal/network/SimpleCallback.java
  application_new/app/src/main/java/com/capstone/apppal/network/handler/SocketReceiveHandler.java
  application_new/app/src/main/java/com/capstone/apppal/utils/CommonFunctions.java
  application_new/app/src/main/java/com/capstone/apppal/utils/GlobalState.java
  application_new/app/src/main/java/com/capstone/apppal/view/dialog/ConfirmDialog.java
  application_new/app/src/main/java/com/capstone/apppal/view/dialog/InputDialog.java
  application_new/app/src/main/java/com/capstone/apppal/view/fragments/ListFragment.java
  application_new/app/src/main/java/com/capstone/apppal/view/fragments/LoginFragment.java
  application_new/app/src/main/res/layout/activity_main.xml
  application_new/app/src/main/res/layout/dialog_confirm.xml
Labels: development, enhancement

#97 feat(Socket address)
  SocketServer/server.py
Labels: enhancement
